"""up/down vote

Revision ID: c941671e1e6f
Revises: b489499a8f4a
Create Date: 2020-12-05 17:56:52.579429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c941671e1e6f'
down_revision = 'b489499a8f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('down_vote_cnt', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('up_vote_cnt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'up_vote_cnt')
    op.drop_column('post', 'down_vote_cnt')
    # ### end Alembic commands ###
